### ISSUE TITLE
Extend RequestParameter with getters that supports default values

### ISSUE THREAD

**Issue by pk-work** [eclipse-vertx/vertx-openapi#14]
If you have e.g. a query parameter that is optional and not part of the request, the `RequestValidator` will create a new `RequestParameterImpl(null)` and stores it in the `ValidatedRequest`.

If I now want to access the value I have always to do a null check:
```
RequestParameter myList = validatedRequest.getQuery().get("myList");
List<String> list = myList.isNull() ? List.of() : myList .getJsonArray().getList();
```
I'd like to have convenience methods, like `#getJsonArray(JsonArray default)` 
```
RequestParameter myList = validatedRequest.getQuery().get("myList");
List<String> list = myList.getJsonArray(new JsonArray()).getList();
```

What do you think?

**Comment by thced** [comment]
Maybe support Supplier, for lazy behavior?

**Comment by CheesyBoy123** [comment]
Hey @pk-work / @thced Happy new years! I saw this issue and it seemed pretty simple to me so I took a stab at it. I added convenience functions that take in a Supplier so if the value is null, it will return that default value instead. If you want to take a look! https://github.com/eclipse-vertx/vertx-openapi/pull/52
