### ISSUE TITLE
Add support for application/hal+json

### ISSUE THREAD

**Issue by CheesyBoy123** [eclipse-vertx/vertx-openapi#59]
#### Describe the feature

Application HAL json is a type of JSON that internal applications use. Previously with the old vertx-web-api-contract we were able to create our schemas with application/hal+json with normal json validations.

More information here:
https://stateless.group/hal_specification.html
https://datatracker.ietf.org/doc/html/draft-kelly-json-hal#name-requirements

#### Use cases

Any Rest API that would be supporting application/hal+json

#### Contribution

Who should implement this feature ? are you volunteering for implementing this feature or
do you know that is able and willing implement this feature ?

**Comment by pk-work** [comment]
Done. It is also down ported into 4.x
